### ISSUE TITLE
dynamic libs pkgutils building

### ISSUE THREAD

**Issue by scsijon** [Vifon/pkgutils#1]
More of a fyi than problem, maybe worth adding to your README at least unless you want to add a test for it and case set if yes/no.

https://www.linuxquestions.org/questions/slackware-14/error-while-building-pkgutils-4175501725/

**Comment by scsijon** [comment]
I take it back, it seems you have already done so already, so i'm closing it

**Comment by vifon** [comment]
Hm, I did? :)

**Comment by scsijon** [comment]
well someone did?

**Comment by vifon** [comment]
Which part of the README do you mean exactly?

**Comment by scsijon** [comment]
On 07/09/19 19:27, Wojciech Siewierski wrote:
> Which part of the README do you mean exactly?
> 
the one related to the one in the link
